#apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-celery-beat
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-celery-beat
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-celery-beat
        version: {{ .Chart.Version }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: hello-world
          imagePullPolicy: Always
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["./deployment/run_celery_beat.sh"]
          env:
            - name: ENV_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
                  key: django-db-connection-string
            - name: FCM_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
                  key: fcm-key
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
                  key: celery-broker-url


      imagePullSecrets:
        - name: regcred