version: '2'

services:
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#    ports:
#      - "5432:5432"
  # Redis
  redis:
    image: redis
    hostname: redis

  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "5672:5672"  # we forward this port because it's useful for debugging
      - "15672:15672"  # here, we can access rabbitmq management plugin

  # Django web server
  web:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    hostname: web
    command: ./deployment/run_web.sh
    stop_signal: KILL
    volumes:
      - ..:/code  # mount current directory inside container, preserve media and static across restarts
      - /my_django_data/:/my_django_data
    expose:
    # uwsgi port
      - "8000"
    # set up links so that web knows about db, rabbit and redis
    links:
      - rabbit
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - LOGGING_CUSTOM_TAGS=${LOGGING_CUSTOM_TAGS}


  # Celery worker
  worker:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    command: ./deployment/run_celery.sh
    volumes:
      - ..:/code
      - /my_django_data/:/my_django_data
    links:
      - rabbit
      - redis
    depends_on:
      - rabbit
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - LOGGING_CUSTOM_TAGS=celery;${LOGGING_CUSTOM_TAGS}

  nginx-certbot:
    ports:
      - "80:80"
      - "443:443"
    restart: always
    build:
      context: ./nginx-certbot
      dockerfile: ./Dockerfile
    volumes:
      - ./nginx-certbot/:/cert_folder/
      - /my_django_data/https_certs/:/etc/letsencrypt
      - /my_django_data/static/:/my_django_data/static
      - /my_django_data/media/:/my_django_data/media
    environment:
      - DOMAIN=${DOMAIN}
      - ENABLE_REDIRECT=${ENABLE_REDIRECT}