apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
  labels:
    app: {{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}
    version: {{ .Chart.Version }}
    release: {{ .Release.Name }}
type: Opaque
data:
  django-db-connection-string: postgres://postgres:Uc7hFNfeA7@singing-ferrit-postgresql/postgres
  celery-broker-url: amqp://guest:guest@{{ printf "%s-%s" .Release.Name .Chart.Name | trunc 63 }}-rabbit:5672//
#  rabbit-default-user: admin
#  rabbit-default-pass: mypass

